### ISSUE TITLE
[Pailot-P0] Implement a middleware for uploading file Images using Cloudinary

### ISSUE THREAD

**Issue by vyktoremario** [pi-apps/pailot-for-pi#26]
We will need a middleware that receives the images, uploads them to Cloudinary and returns a URL string to be saved in the database.

You can check out video tutorials about this if you are not sure how it works or read the documentation https://cloudinary.com/documentation/node_integration

**Comment by Saneeitas** [comment]
Okay

**Comment by vyktoremario** [comment]
Closed by #31
